# use for develop frontend
version: "3.9"

services:
  ocserv_and_backend:
    restart: always
    image: ocserv_and_backend:ocserv
    container_name: ocserv_and_backend_for_frontend
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - 20443:443/tcp
      - 20443:443/udp
      - 127.0.0.1:8000:8000
    environment:
      - CN=End-way-Cisco-VPN
      - ORG=End-way
      - EXPIRE=3650
      - OC_NET=172.16.24.0/24
      - DEBUG=True
      - CORS_ALLOWED=http://127.0.0.1:9000
      - SECRET_KEY=SECRET_KEY
      - SOCKET_PASSWD_FILE=./back-end/socket_passwd.txt
    volumes:
      - "./back-end:/app"
      - "./volumes/ocserv:/etc/ocserv"
      - "./volumes/log:/var/log"

  monitor:
    image: golang:latest
    container_name: monitor
    build:
      context: .
      dockerfile: Dockerfile.Monitor
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - SOCKET_PASSWD_FILE=/tmp/socket_passwd.txt
      - LOG_FILE=/var/log/ocserv.log
    volumes:
      - "./back-end/socket_passwd.txt:/tmp/socket_passwd.txt"
      - "./volumes/log/ocserv.log:/var/log/ocserv.log"
#
#
#
# DOCKER_SCAN_SUGGEST=false docker compose -f docker-compose.dev.yml up -d --build
