version: "3.9"

services:
  ocserv_and_backend:
    restart: always
    image: ocserv_and_backend:ocserv_dev
    container_name: ocserv_and_backend_for_frontend
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - 20443:443/tcp
      - 20443:443/udp
      - 127.0.0.1:8000:8000
    env_file:
      - dev.env
    volumes:
      - ./back-end:/app
      - ./volumes/ocserv:/etc/ocserv
#
#
#
# DOCKER_SCAN_SUGGEST=false docker compose -f docker-compose.dev.yml up -d --build
