version: "3.9"

volumes:
  shared-ssl:
  # shared-mointor:

services:
  ocserv_and_backend:
    restart: always
    image: ocserv_and_backend:ocserv
    container_name: ocserv_and_backend
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.Pack
    volumes:
      - ./volumes/ocserv:/etc/ocserv
      - ./volumes/db:/app/db
      - shared-ssl:/etc/ocserv/certs
      # - shared-mointor:/var/log
    ports:
      - ${PORT:-20443}:443/tcp
      - ${PORT:-20443}:443/udp
      - 127.0.0.1:8000:8000
    env_file:
      - prod.env

  nginx:
    restart: always
    image: nginx:ocserv
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.Front
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ocserv_and_backend
      - monitor
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - shared-ssl:/etc/nginx/certs

  # monitor:
  #   restart: on-failure
  #   image: monitor:ocserv
  #   container_name: monitor
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.Monitor
  #   volumes:
  #     - shared-mointor:/shared_mointor
  #   depends_on:
  #     - ocserv_and_backend
